#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

STABLE_BINDINGS_PATH="${1:-${REPO_ROOT}/crates/rrad_pjrt/src/ffi/pjrt_bindings.rs}"
LATEST_BINDINGS_PATH="${2:-${STABLE_BINDINGS_PATH}}"
OUT_PATH="${3:-${REPO_ROOT}/crates/rrad_pjrt/PJRT_BINDING_DIFF.md}"

if [[ ! -f "${STABLE_BINDINGS_PATH}" ]]; then
  echo "Error: stable bindings file not found: ${STABLE_BINDINGS_PATH}" >&2
  exit 1
fi

if [[ ! -f "${LATEST_BINDINGS_PATH}" ]]; then
  echo "Error: latest bindings file not found: ${LATEST_BINDINGS_PATH}" >&2
  exit 1
fi

mkdir -p "$(dirname "${OUT_PATH}")"

stable_symbols_file="$(mktemp)"
latest_symbols_file="$(mktemp)"
stable_only_file="$(mktemp)"
latest_only_file="$(mktemp)"
common_file="$(mktemp)"
trap 'rm -f "${stable_symbols_file}" "${latest_symbols_file}" "${stable_only_file}" "${latest_only_file}" "${common_file}"' EXIT

extract_api_symbols() {
  local bindings_file="$1"
  local out_file="$2"

  sed -n '/pub struct PJRT_Api {/,/^}/p' "${bindings_file}" \
    | grep -E '^[[:space:]]*pub PJRT_' \
    | sed -E 's/^[[:space:]]*pub (PJRT_[A-Za-z0-9_]+):.*/\1/' \
    | LC_ALL=C sort -u \
    > "${out_file}"
}

extract_api_symbols "${STABLE_BINDINGS_PATH}" "${stable_symbols_file}"
extract_api_symbols "${LATEST_BINDINGS_PATH}" "${latest_symbols_file}"

comm -23 "${stable_symbols_file}" "${latest_symbols_file}" > "${stable_only_file}"
comm -13 "${stable_symbols_file}" "${latest_symbols_file}" > "${latest_only_file}"
comm -12 "${stable_symbols_file}" "${latest_symbols_file}" > "${common_file}"

stable_count="$(wc -l < "${stable_symbols_file}" | tr -d ' ')"
latest_count="$(wc -l < "${latest_symbols_file}" | tr -d ' ')"
common_count="$(wc -l < "${common_file}" | tr -d ' ')"
stable_only_count="$(wc -l < "${stable_only_file}" | tr -d ' ')"
latest_only_count="$(wc -l < "${latest_only_file}" | tr -d ' ')"

{
  echo "# PJRT Binding Diff"
  echo
  echo "This file is auto-generated by \`crates/rrad_pjrt/scripts/update_pjrt_binding_diff.sh\`."
  echo "It compares stable bindings vs latest PJRT header bindings."
  echo
  echo "## Summary"
  echo
  echo "- Stable PJRT API symbols: ${stable_count}"
  echo "- Latest PJRT API symbols: ${latest_count}"
  echo "- Symbols in both: ${common_count}"
  echo "- Stable-only symbols (not in latest): ${stable_only_count}"
  echo "- Latest-only symbols (new additions not in stable): ${latest_only_count}"
  echo
  echo "## Latest Additions Not In Stable"
  echo
  if [[ "${latest_only_count}" -eq 0 ]]; then
    echo "- None"
  else
    while IFS= read -r symbol; do
      [[ -z "${symbol}" ]] && continue
      echo "- \`${symbol}\`"
    done < "${latest_only_file}"
  fi

  echo
  echo "## Stable-Only Not In Latest"
  echo
  if [[ "${stable_only_count}" -eq 0 ]]; then
    echo "- None"
  else
    while IFS= read -r symbol; do
      [[ -z "${symbol}" ]] && continue
      echo "- \`${symbol}\`"
    done < "${stable_only_file}"
  fi
} > "${OUT_PATH}"

echo "Updated ${OUT_PATH}"
