#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

BINDINGS_PATH="${1:-${REPO_ROOT}/crates/rrad_pjrt/src/ffi/pjrt_bindings.rs}"
OUT_PATH="${2:-${REPO_ROOT}/crates/rrad_pjrt/PJRT_BINDING_DIFF.md}"
SRC_DIR="${3:-${REPO_ROOT}/crates/rrad_pjrt/src}"

if [[ ! -f "${BINDINGS_PATH}" ]]; then
  echo "Error: bindings file not found: ${BINDINGS_PATH}" >&2
  exit 1
fi

if [[ ! -d "${SRC_DIR}" ]]; then
  echo "Error: source directory not found: ${SRC_DIR}" >&2
  exit 1
fi

mkdir -p "$(dirname "${OUT_PATH}")"

api_symbols_file="$(mktemp)"
unsupported_file="$(mktemp)"
trap 'rm -f "${api_symbols_file}" "${unsupported_file}"' EXIT

sed -n '/pub struct PJRT_Api {/,/^}/p' "${BINDINGS_PATH}" \
  | grep -E '^[[:space:]]*pub PJRT_' \
  | sed -E 's/^[[:space:]]*pub (PJRT_[A-Za-z0-9_]+):.*/\1/' \
  > "${api_symbols_file}"

total_symbols="$(wc -l < "${api_symbols_file}" | tr -d ' ')"
supported_symbols=0

while IFS= read -r symbol; do
  [[ -z "${symbol}" ]] && continue

  if grep -R -E -q "\\b${symbol}\\b" "${SRC_DIR}" \
      --exclude-dir=ffi \
      --exclude='pjrt_bindings.rs'; then
    supported_symbols=$((supported_symbols + 1))
  else
    echo "${symbol}" >> "${unsupported_file}"
  fi
done < "${api_symbols_file}"

unsupported_symbols="$(wc -l < "${unsupported_file}" | tr -d ' ')"

{
  echo "# PJRT Binding Diff"
  echo
  echo "This file is auto-generated by \`crates/rrad_pjrt/scripts/update_pjrt_binding_diff.sh\`."
  echo "It tracks PJRT C API symbols in \`pjrt_bindings.rs\` that are not yet referenced by \`rrad_pjrt\` source (excluding generated FFI files)."
  echo
  echo "## Summary"
  echo
  echo "- Total PJRT API symbols in bindings: ${total_symbols}"
  echo "- Symbols referenced in \`rrad_pjrt/src\`: ${supported_symbols}"
  echo "- Symbols not yet referenced: ${unsupported_symbols}"
  echo
  echo "## Not Yet Supported"
  echo
  if [[ "${unsupported_symbols}" -eq 0 ]]; then
    echo "- None"
  else
    while IFS= read -r symbol; do
      [[ -z "${symbol}" ]] && continue
      echo "- \`${symbol}\`"
    done < "${unsupported_file}"
  fi
} > "${OUT_PATH}"

echo "Updated ${OUT_PATH}"
